services:
  nginx:
    image: nginx:1.23
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/azureuser/SEP490_G12_MP-BHMS/img/ocr:/usr/share/nginx/html/img/ocr:rw
      # Mount uploads to a consistent absolute path used by both nginx and backend
      - /home/azureuser/SEP490_G12_MP-BHMS/uploads:/uploads:ro

    ports:
      - "80:80"
      - "443:443"
  db-mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_DATABASE=mpbhms
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    expose:
      - "3306"

  backend-spring:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mpbhms?serverTimezone=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MPBHMS_UPLOAD_FILE_BASE_URI=file:///uploads/
      - FILE_UPLOAD_DIR=/uploads
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - db-mysql
    volumes:
      - /home/azureuser/SEP490_G12_MP-BHMS/uploads:/uploads
      - /home/azureuser/SEP490_G12_MP-BHMS/img/ocr:/usr/share/nginx/html/img/ocr
    # docker compose -p mpbhms-spring-rest up -d
